// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: ***REMOVED***,
    appId: ***REMOVED***,
    messagingSenderId: ***REMOVED***,
    projectId: ***REMOVED***,
    authDomain: ***REMOVED***,
    databaseURL: ***REMOVED***,
    storageBucket: ***REMOVED***,
    measurementId: ***REMOVED***,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: ***REMOVED***,
    appId: ***REMOVED***,
    messagingSenderId: ***REMOVED***,
    projectId: ***REMOVED***,
    databaseURL: ***REMOVED***,
    storageBucket: ***REMOVED***,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: ***REMOVED***,
    appId: ***REMOVED***,
    messagingSenderId: ***REMOVED***,
    projectId: ***REMOVED***,
    databaseURL: ***REMOVED***,
    storageBucket: ***REMOVED***,
    iosBundleId: 'com.centinela.custodes',
  );
}
