name: Build Release App Bundle

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: 'android/app/keystore/centinela.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - name: List keystore directory
        run: ls -l android/app/keystore/
      - name: Testing another directory
        run: ls -l Custodes/android/app/keystore/