name: Auto Pull Request

on:
  push:
    branches:
      - logos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup git config
        run: |
          # setup the username and email
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Create Pull Request
        run: |
          changedFiles=$(git diff --name-only HEAD^ HEAD | grep '^assets/')
          commitCount=$(git rev-list --count HEAD^ HEAD)

          if [[ $changedFiles -ge 10 || $commitCount -ge 10 ]]; then
            echo "Creating pull request..."
            gh pr create -B app-prealpha -H logos --title "Automated Logos Pull Request" --body "Changed Files:\n$changedFiles\n\nCommits Count: $commitCount"
          else
            echo "Conditions not met. No pull request created."
          fi
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}