name: Auto Pull Request
on:
  push:
    branches:
      - logos
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch and get info
      - name: checkout - Check changed files and commit count
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      #Debug print lol
      - run: |
          set -e  # Enable error handling
          changedFiles=$(git diff --name-only HEAD^ HEAD | grep '^assets/' || true)
          echo "Changed Files: ${changedFiles}"
          commitCount=$(git rev-list --count HEAD^ HEAD)
          echo "Commits Count: ${commitCount}"
          baseBranch="logos"
          toMergeToBranch="app-prealpha"

      #What, why?
      #- name: Setup git config
      #  run: |
          # setup the username and email
      #    git config user.name "GitHub Actions Bot"
      #    git config user.email "<>"

      - name: Create Pull Request
        run: |
          if [[ $changedFiles -ge 10 || $commitCount -ge 10 ]]; then
            echo "Creating pull request..."
            gh pr create -B $toMergeToBranch -H $baseBranch --title "Automated ${baseBranch} Pull Request" --body "Changed Files:\n$changedFiles\n\nCommits Count: $commitCount"
          else
            echo "Conditions not met. No pull request created."
          fi
          
      - name: Echo mergeable PR number
        run: echo ${{ steps.open_pr.outputs.pull_number }}