name: Auto Pull Request

on:
  push:
    branches:
      - logos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout - Get access to git repo stuff
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check changed files and commit count
        id: check_changes
        run: |
          export CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep '^assets/' || echo "No changes in assets folder")
          echo "Changed Files: ${CHANGED_FILES}"

          export COMMIT_COUNT=$(git rev-list --count HEAD^ HEAD)
          echo "Commits Count: ${COMMIT_COUNT}"

          # Set outputs
          echo "${CHANGED_FILES}" >> $GITHUB_WORKSPACE/envFile1.txt
          echo "${COMMIT_COUNT}" >> $GITHUB_WORKSPACE/envFile2.txt

  create_pr:
    runs-on: ubuntu-latest
    needs: build
    steps:
    #Fr?
      - name: Checkout again
        uses: actions/checkout@v4
        with:
          # Fetch the entire history again
          fetch-depth: 0
      - name: Create Pull Request
        run: |
          echo "Environment Variables:"
          CHANGED_FILES=$(cat $GITHUB_WORKSPACE/envFile1.txt)
          COMMIT_COUNT=$(cat $GITHUB_WORKSPACE/envFile2.txt)
          echo "CHANGED_FILES: ${CHANGED_FILES}"
          echo "COMMIT_COUNT: ${COMMIT_COUNT}"
          baseBranch="logos"
          toMergeToBranch="app-prealpha"
          if [[ "${{ needs.build.outputs.CHANGED_FILES }}" == "No changes in assets folder" || -z "${{ needs.build.outputs.COMMIT_COUNT }}" ]]; then
            echo "Either CHANGED_FILES is 'No changes in assets folder' or COMMIT_COUNT is empty."
          elif [[ "${{ needs.build.outputs.COMMIT_COUNT }}" -ge 10 ]]; then
            echo "COMMIT_COUNT is greater than or equal to 10."
            echo "Creating pull request..."
            gh pr create -B $toMergeToBranch -H $baseBranch --title "Automated ${baseBranch} Pull Request" --body "Changed Files:\n${{ needs.build.outputs.CHANGED_FILES }}\n\nCommits Count: ${{ needs.build.outputs.COMMIT_COUNT }}"
          else
            echo "Conditions not met. No pull request created."
          fi