name: Auto Pull Request

on:
  push:
    branches:
      - logos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request
        run: |
          echo "Current commit SHA: ${GITHUB_SHA}"
          changedFiles=$(git diff --name-only ${GITHUB_SHA}^ ${GITHUB_SHA} | grep '^assets/')
          echo "Changed Files: ${changedFiles}"
          commitCount=$(git rev-list --count ${GITHUB_EVENT_BEFORE}..${GITHUB_SHA})
          echo "Commits Count: ${commitCount}"

          if [[ $changedFiles -ge 10 || $commitCount -ge 10 ]]; then
            echo "Creating pull request..."
            gh pr create -B app-prealpha -H logos --title "Automated Logos Pull Request" --body "Changed Files:\n$changedFiles\n\nCommits Count: $commitCount"
          else
            echo "Conditions not met. No pull request created."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

