name: Auto Pull Request

on:
  push:
    branches:
      - logos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request
        run: |
          changedFiles=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^assets/')
          commitCount=$(git rev-list --count ${{ github.event.before }}..${{ github.sha }})

          if [[ $changedFiles -ge 10 || $commitCount -ge 10 ]]; then
            echo "Creating pull request..."
            gh pr create -B app-prealpha -H logos --title "Automated Logos Pull Request" --body "Changed Files:\n$changedFiles\n\nCommits Count: $commitCount"
          else
            echo "Conditions not met. No pull request created."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}